services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mv-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      SA_PASSWORD: "Admin_sa1!"
    ports:
      - "1443:1433"
    volumes:
      - mssqldata:/var/opt/mssql
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"Admin_sa1!\" -C -Q \"SELECT 1\"" ]
      interval: 10s
      timeout: 3s
      retries: 30

  web:
    build:
      context: .
      dockerfile: apps/frontend/src/Morning.Value.Web.Site/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__Local: "Server=db;Database=MorningValue;User ID=sa;Password=Admin_sa1!;Encrypt=True;TrustServerCertificate=True"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  mssqldata:
