name: CI

on:
  push:
    branches: [ main ]
    paths:
      - "**/*.sln"
      - "**/*.csproj"
      - "**/*.cs"
      - ".github/workflows/ci.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "**/*.sln"
      - "**/*.csproj"
      - "**/*.cs"
      - ".github/workflows/ci.yml"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      COV_ASSEMBLY_FILTER: "+Morning.Value.*"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Cache NuGet packages
        id: cache_nuget
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Cache status
        shell: bash
        run: |
          echo "NuGet cache hit: ${{ steps.cache
